#!/bin/sh
printf '%s\n' \
    'usage: go [--version] <command> [<args>]' \
    '' \
    'These are common Go commands used in various situations:' \
    '' \
    'start a working area (see also: go help tutorial)' \
    '   clone      Clone a repository into a new directory' \
    '   init       Create an empty Go repository' \
    '' \
    'work on the current change (see also: go help everyday)' \
    '   add        Add file contents to the index' \
    '   mv         Move or rename a file, a directory, or a symlink' \
    '   restore    Restore working tree files' \
    '' \
    'examine the history and state (see also: go help revisions)' \
    '   diff       Show changes between commits' \
    '   log        Show commit logs' \
    '   status     Show the working tree status'
