#pragma once

#include "Common.hpp"
#include "StaticStringMap.hpp"

namespace shit {

namespace completion {

inline constexpr PackedStringKey TRANSPARENT_PREFIX_KEYS[] = {
    SSK("!"),    SSK("time"), SSK("if"),      SSK("then"),
    SSK("else"), SSK("elif"), SSK("while"),   SSK("until"),
    SSK("do"),   SSK("{"),    SSK("sudo"),    SSK("doas"),
    SSK("env"),  SSK("nice"), SSK("command"), SSK("builtin"),
};
inline constexpr StaticStringSet TRANSPARENT_PREFIXES{TRANSPARENT_PREFIX_KEYS};

inline constexpr static_string_entry<const char *>
    FILE_EXTENSION_HINT_ENTRIES[] = {
        {SSK("unzip"),    "zip"                                                   },
        {SSK("gunzip"),   "gz"                                                    },
        {SSK("zcat"),     "gz"                                                    },
        {SSK("bunzip2"),  "bz2"                                                   },
        {SSK("bzcat"),    "bz2"                                                   },
        {SSK("unxz"),     "xz"                                                    },
        {SSK("xzcat"),    "xz"                                                    },
        {SSK("unzstd"),   "zst zstd"                                              },
        {SSK("zstdcat"),  "zst zstd"                                              },
        {SSK("unlzma"),   "lzma"                                                  },
        {SSK("lzcat"),    "lzma"                                                  },
        {SSK("unrar"),    "rar"                                                   },
        {SSK("lz4cat"),   "lz4"                                                   },
        {SSK("7z"),       "7z"                                                    },
        {SSK("7za"),      "7z"                                                    },
        {SSK("7zr"),      "7z"                                                    },
        {SSK("tar"),      "tar tgz tbz2 txz tzst gz bz2 xz zst"                   },
        {SSK("feh"),      "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("sxiv"),     "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("nsxiv"),    "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("imv"),      "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("qiv"),      "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("gpicview"), "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("display"),  "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("animate"),  "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("eog"),      "png jpg jpeg gif bmp webp tiff svg ico"                },
        {SSK("mpv"),      "mp4 mkv webm avi mov flv mp3 flac wav ogg opus m4a aac"},
        {SSK("vlc"),      "mp4 mkv webm avi mov flv mp3 flac wav ogg opus m4a aac"},
        {SSK("mplayer"),
         "mp4 mkv webm avi mov flv mp3 flac wav ogg opus m4a aac"                 },
        {SSK("ffplay"),
         "mp4 mkv webm avi mov flv mp3 flac wav ogg opus m4a aac"                 },
        {SSK("totem"),    "mp4 mkv webm avi mov flv"                              },
        {SSK("mupdf"),    "pdf epub xps cbz"                                      },
        {SSK("zathura"),  "pdf ps epub cbz cbr djvu"                              },
        {SSK("evince"),   "pdf ps epub djvu"                                      },
        {SSK("okular"),   "pdf ps epub djvu cbz"                                  },
        {SSK("xpdf"),     "pdf"                                                   },
};
inline constexpr StaticStringMap FILE_EXTENSION_HINTS{
    FILE_EXTENSION_HINT_ENTRIES};

inline constexpr static_string_entry<const char *> MANPAGE_ALIAS_ENTRIES[] = {
    {SSK("clang++"), "clang"},
    {SSK("c++"),     "clang"},
    {SSK("g++"),     "gcc"  },
};
inline constexpr StaticStringMap MANPAGE_ALIASES{MANPAGE_ALIAS_ENTRIES};

enum class tool_with_targets_kind : u8
{
  make,
  ninja,
  cmake,
  node_runner,
  ssh,
  teleport,
};

inline constexpr static_string_entry<tool_with_targets_kind>
    TOOL_WITH_TARGETS_ENTRIES[] = {
        {SSK("make"),        tool_with_targets_kind::make       },
        {SSK("ninja"),       tool_with_targets_kind::ninja      },
        {SSK("cmake"),       tool_with_targets_kind::cmake      },
        {SSK("npm"),         tool_with_targets_kind::node_runner},
        {SSK("yarn"),        tool_with_targets_kind::node_runner},
        {SSK("pnpm"),        tool_with_targets_kind::node_runner},
        {SSK("bun"),         tool_with_targets_kind::node_runner},
        {SSK("ssh"),         tool_with_targets_kind::ssh        },
        {SSK("scp"),         tool_with_targets_kind::ssh        },
        {SSK("sftp"),        tool_with_targets_kind::ssh        },
        {SSK("rsync"),       tool_with_targets_kind::ssh        },
        {SSK("mosh"),        tool_with_targets_kind::ssh        },
        {SSK("telnet"),      tool_with_targets_kind::ssh        },
        {SSK("ssh-copy-id"), tool_with_targets_kind::ssh        },
        {SSK("sshfs"),       tool_with_targets_kind::ssh        },
        {SSK("autossh"),     tool_with_targets_kind::ssh        },
        {SSK("tsh"),         tool_with_targets_kind::teleport   },
};
inline constexpr StaticStringMap TOOLS_WITH_TARGETS{TOOL_WITH_TARGETS_ENTRIES};

inline constexpr static_string_entry<const char *> HELP_ALLOWLIST_ENTRIES[] = {
    {SSK("ffmpeg"),              "--help full"},
    {SSK("ffprobe"),             "--help full"},
    {SSK("ffplay"),              "--help full"},
    {SSK("cargo"),               "--help"     },
    {SSK("tailscale"),           "--help"     },
    {SSK("tsh"),                 "--help"     },
    {SSK("zb"),                  "--help"     },
    {SSK("brew"),                "--help"     },
    {SSK("clan"),                "--help"     },
    {SSK("oo"),                  "--help"     },
    {SSK("rustup"),              "--help"     },
    {SSK("rustc"),               "--help"     },
    {SSK("rustfmt"),             "--help"     },
    {SSK("go"),                  "help"       },
    {SSK("npm"),                 "--help"     },
    {SSK("pnpm"),                "--help"     },
    {SSK("yarn"),                "--help"     },
    {SSK("deno"),                "--help"     },
    {SSK("bun"),                 "--help"     },
    {SSK("node"),                "--help"     },
    {SSK("pip"),                 "--help"     },
    {SSK("pip3"),                "--help"     },
    {SSK("docker"),              "--help"     },
    {SSK("podman"),              "--help"     },
    {SSK("kubectl"),             "--help"     },
    {SSK("helm"),                "--help"     },
    {SSK("gh"),                  "--help"     },
    {SSK("glab"),                "--help"     },
    {SSK("terraform"),           "--help"     },
    {SSK("cmake"),               "--help"     },
    {SSK("ninja"),               "--help"     },
    {SSK("meson"),               "--help"     },
    {SSK("jq"),                  "--help"     },
    {SSK("yq"),                  "--help"     },
    {SSK("rg"),                  "--help"     },
    {SSK("fd"),                  "--help"     },
    {SSK("bat"),                 "--help"     },
    {SSK("fzf"),                 "--help"     },
    {SSK("zig"),                 "--help"     },
    {SSK("poetry"),              "--help"     },
    {SSK("pipx"),                "--help"     },
    {SSK("uv"),                  "--help"     },
    {SSK("just"),                "--help"     },
    {SSK("hugo"),                "--help"     },
    {SSK("pandoc"),              "--help"     },
    {SSK("delta"),               "--help"     },
    {SSK("dust"),                "--help"     },
    {SSK("starship"),            "--help"     },
    {SSK("gofmt"),               "--help"     },
    {SSK("magick"),              "--help"     },
    {SSK("convert"),             "--help"     },
    {SSK("clang"),               "--help"     },
    {SSK("clang++"),             "--help"     },
    {SSK("gcc"),                 "--help"     },
    {SSK("g++"),                 "--help"     },
    {SSK("cc"),                  "--help"     },
    {SSK("c++"),                 "--help"     },
    {SSK("clang-format"),        "--help"     },
    {SSK("clang-tidy"),          "--help"     },
    {SSK("gdb"),                 "--help"     },
    {SSK("lldb"),                "--help"     },
    {SSK("objdump"),             "--help"     },
    {SSK("readelf"),             "--help"     },
    {SSK("nm"),                  "--help"     },
    {SSK("strip"),               "--help"     },
    {SSK("ar"),                  "--help"     },
    {SSK("ld"),                  "--help"     },
    {SSK("lld"),                 "--help"     },
    {SSK("valgrind"),            "--help"     },
    {SSK("cppcheck"),            "--help"     },
    {SSK("ccache"),              "--help"     },
    {SSK("adb"),                 "--help"     },
    {SSK("fastboot"),            "--help"     },
    {SSK("waydroid"),            "--help"     },
    {SSK("python"),              "--help"     },
    {SSK("python3"),             "--help"     },
    {SSK("ruby"),                "--help"     },
    {SSK("perl"),                "--help"     },
    {SSK("lua"),                 "--help"     },
    {SSK("php"),                 "--help"     },
    {SSK("julia"),               "--help"     },
    {SSK("java"),                "--help"     },
    {SSK("javac"),               "--help"     },
    {SSK("kotlin"),              "--help"     },
    {SSK("kotlinc"),             "--help"     },
    {SSK("scala"),               "--help"     },
    {SSK("dotnet"),              "--help"     },
    {SSK("dart"),                "--help"     },
    {SSK("swift"),               "--help"     },
    {SSK("swiftc"),              "--help"     },
    {SSK("elixir"),              "--help"     },
    {SSK("mix"),                 "--help"     },
    {SSK("ocaml"),               "--help"     },
    {SSK("crystal"),             "--help"     },
    {SSK("nim"),                 "--help"     },
    {SSK("cabal"),               "--help"     },
    {SSK("stack"),               "--help"     },
    {SSK("opam"),                "--help"     },
    {SSK("ghc"),                 "--help"     },
    {SSK("tsc"),                 "--help"     },
    {SSK("esbuild"),             "--help"     },
    {SSK("prettier"),            "--help"     },
    {SSK("eslint"),              "--help"     },
    {SSK("biome"),               "--help"     },
    {SSK("vite"),                "--help"     },
    {SSK("ansible"),             "--help"     },
    {SSK("ansible-config"),      "--help"     },
    {SSK("ansible-console"),     "--help"     },
    {SSK("ansible-doc"),         "--help"     },
    {SSK("ansible-galaxy"),      "--help"     },
    {SSK("ansible-inventory"),   "--help"     },
    {SSK("ansible-playbook"),    "--help"     },
    {SSK("ansible-pull"),        "--help"     },
    {SSK("ansible-test"),        "--help"     },
    {SSK("ansible-vault"),       "--help"     },
    {SSK("typst"),               "--help"     },
    {SSK("apt"),                 "--help"     },
    {SSK("apt-get"),             "--help"     },
    {SSK("dnf"),                 "--help"     },
    {SSK("pacman"),              "--help"     },
    {SSK("zypper"),              "--help"     },
    {SSK("apk"),                 "--help"     },
    {SSK("brew"),                "--help"     },
    {SSK("flatpak"),             "--help"     },
    {SSK("snap"),                "--help"     },
    {SSK("nix"),                 "--help"     },
    {SSK("nix-store"),           "--help"     },
    {SSK("nix-shell"),           "--help"     },
    {SSK("nix-build"),           "--help"     },
    {SSK("nix-channel"),         "--help"     },
    {SSK("nix-daemon"),          "--help"     },
    {SSK("nix-env"),             "--help"     },
    {SSK("nix-hash"),            "--help"     },
    {SSK("conda"),               "--help"     },
    {SSK("mamba"),               "--help"     },
    {SSK("gem"),                 "--help"     },
    {SSK("composer"),            "--help"     },
    {SSK("hg"),                  "--help"     },
    {SSK("svn"),                 "--help"     },
    {SSK("jj"),                  "--help"     },
    {SSK("fossil"),              "--help"     },
    {SSK("eza"),                 "--help"     },
    {SSK("lsd"),                 "--help"     },
    {SSK("procs"),               "--help"     },
    {SSK("sd"),                  "--help"     },
    {SSK("hyperfine"),           "--help"     },
    {SSK("tokei"),               "--help"     },
    {SSK("watchexec"),           "--help"     },
    {SSK("entr"),                "--help"     },
    {SSK("direnv"),              "--help"     },
    {SSK("zoxide"),              "--help"     },
    {SSK("atuin"),               "--help"     },
    {SSK("broot"),               "--help"     },
    {SSK("btm"),                 "--help"     },
    {SSK("gitui"),               "--help"     },
    {SSK("dive"),                "--help"     },
    {SSK("k9s"),                 "--help"     },
    {SSK("kubectx"),             "--help"     },
    {SSK("kubens"),              "--help"     },
    {SSK("kustomize"),           "--help"     },
    {SSK("skaffold"),            "--help"     },
    {SSK("flamegraph"),          "--help"     },
    {SSK("doctl"),               "--help"     },
    {SSK("flyctl"),              "--help"     },
    {SSK("pulumi"),              "--help"     },
    {SSK("packer"),              "--help"     },
    {SSK("vault"),               "--help"     },
    {SSK("consul"),              "--help"     },
    {SSK("nomad"),               "--help"     },
    {SSK("vercel"),              "--help"     },
    {SSK("curl"),                "--help"     },
    {SSK("wget"),                "--help"     },
    {SSK("httpie"),              "--help"     },
    {SSK("xh"),                  "--help"     },
    {SSK("aria2c"),              "--help"     },
    {SSK("rsync"),               "--help"     },
    {SSK("rclone"),              "--help"     },
    {SSK("openvpn"),             "--help"     },
    {SSK("mlr"),                 "--help"     },
    {SSK("dasel"),               "--help"     },
    {SSK("gron"),                "--help"     },
    {SSK("fx"),                  "--help"     },
    {SSK("xsv"),                 "--help"     },
    {SSK("systemctl"),           "--help"     },
    {SSK("journalctl"),          "--help"     },
    {SSK("nmcli"),               "--help"     },
    {SSK("buildah"),             "--help"     },
    {SSK("skopeo"),              "--help"     },
    {SSK("dedoc"),               "--help"     },
    {SSK("git"),                 "--help"     },
    {SSK("git-lfs"),             "--help"     },
    {SSK("lazygit"),             "--help"     },
    {SSK("tig"),                 "--help"     },
    {SSK("tmux"),                "--help"     },
    {SSK("htop"),                "--help"     },
    {SSK("btop"),                "--help"     },
    {SSK("glances"),             "--help"     },
    {SSK("iotop"),               "--help"     },
    {SSK("ip"),                  "--help"     },
    {SSK("ss"),                  "--help"     },
    {SSK("dig"),                 "--help"     },
    {SSK("nmap"),                "--help"     },
    {SSK("ncat"),                "--help"     },
    {SSK("socat"),               "--help"     },
    {SSK("openssl"),             "--help"     },
    {SSK("gpg"),                 "--help"     },
    {SSK("pass"),                "--help"     },
    {SSK("borg"),                "--help"     },
    {SSK("restic"),              "--help"     },
    {SSK("age"),                 "--help"     },
    {SSK("sqlite3"),             "--help"     },
    {SSK("psql"),                "--help"     },
    {SSK("mysql"),               "--help"     },
    {SSK("redis-cli"),           "--help"     },
    {SSK("aws"),                 "--help"     },
    {SSK("gcloud"),              "--help"     },
    {SSK("az"),                  "--help"     },
    {SSK("vagrant"),             "--help"     },
    {SSK("virsh"),               "--help"     },
    {SSK("yt-dlp"),              "--help"     },
    {SSK("youtube-dl"),          "--help"     },
    {SSK("mpc"),                 "--help"     },
    {SSK("ncmpcpp"),             "--help"     },
    {SSK("weechat"),             "--help"     },
    {SSK("newsboat"),            "--help"     },
    {SSK("transmission-remote"), "--help"     },
    {SSK("pre-commit"),          "--help"     },
    {SSK("pytest"),              "--help"     },
    {SSK("black"),               "--help"     },
    {SSK("ruff"),                "--help"     },
    {SSK("mypy"),                "--help"     },
    {SSK("flake8"),              "--help"     },
    {SSK("pylint"),              "--help"     },
    {SSK("shellcheck"),          "--help"     },
    {SSK("shfmt"),               "--help"     },
    {SSK("yamllint"),            "--help"     },
    {SSK("hadolint"),            "--help"     },
    {SSK("actionlint"),          "--help"     },
    {SSK("golangci-lint"),       "--help"     },
    {SSK("protoc"),              "--help"     },
    {SSK("buf"),                 "--help"     },
    {SSK("grpcurl"),             "--help"     },
    {SSK("k6"),                  "--help"     },
    {SSK("mtr"),                 "--help"     },
    {SSK("iperf3"),              "--help"     },
    {SSK("tshark"),              "--help"     },
    {SSK("lsusb"),               "--help"     },
    {SSK("lspci"),               "--help"     },
    {SSK("smartctl"),            "--help"     },
    {SSK("cryptsetup"),          "--help"     },
    {SSK("parted"),              "--help"     },
    {SSK("lsblk"),               "--help"     },
    {SSK("systemd-analyze"),     "--help"     },
    {SSK("machinectl"),          "--help"     },
    {SSK("loginctl"),            "--help"     },
    {SSK("timedatectl"),         "--help"     },
    {SSK("hostnamectl"),         "--help"     },
    {SSK("resolvectl"),          "--help"     },
    {SSK("udevadm"),             "--help"     },
    {SSK("xrandr"),              "--help"     },
    {SSK("xdotool"),             "--help"     },
    {SSK("wmctrl"),              "--help"     },
    {SSK("rofi"),                "--help"     },
    {SSK("dunst"),               "--help"     },
    {SSK("playerctl"),           "--help"     },
    {SSK("brightnessctl"),       "--help"     },
    {SSK("upower"),              "--help"     },
    {SSK("powertop"),            "--help"     },
};
inline constexpr StaticStringMap HELP_ALLOWLIST{HELP_ALLOWLIST_ENTRIES};

} // namespace completion

} // namespace shit
