/*
 *    This file is a part of the Koshka shell, (c) toiletbril, 2026
 *    See the top-level LICENSE file for the licensing information.
 *
 * This file defines the immutable catalog that maps diagnostic identifiers to
 * slugs, messages, suggestions, severity tiers, delivery modes, and optional
 * ShellCheck codes. The static catalog remains outside traversal sources and
 * the public header.
 */

#include "Diagnostics.hpp"
#include "DiagnosticsCatalogInternal.hpp"

namespace koshka {

const diagnostic_definition DIAGNOSTIC_DEFINITIONS[] = {
    D(1000, "literal-dollar-in-quotes",
      "a literal dollar sign is written with a backslash",
      "The `$` at the end of the double-quoted string is read as ordinary text",
      "Write `\\$` inside the quotes", None, Annoying, Policy),
    D(1001, "ineffective-escape", "the backslash before a letter is dropped",
      "The escape `{0}` is read by the shell as a plain '{1}'",
      "Quote the backslash, or build the byte with `printf`", None, Annoying,
      Policy),
    D(1003, "escaped-single-quote",
      "a single-quoted string cannot hold a single quote",
      "A backslash carries no meaning inside single quotes",
      "Write the quote as `'\\''` outside the single-quoted run", None,
      Annoying, Policy),
    D(1004, "escaped-newline-in-quotes",
      "a backslash inside single quotes does not continue the line",
      "The backslash and the line ending are both kept in the single-quoted "
      "text",
      "Close the quote, break the line, and reopen the quote", None, Annoying,
      Policy),
    D(1008, "unrecognized-shebang", "the shebang names an unknown interpreter",
      "The shebang interpreter '{0}' is not a shell this analysis knows",
      "Name a shell such as `sh` or `bash` in the shebang", None, Annoying,
      Policy),
    D(1012, "literal-control-escape",
      "the backslash before a control letter is dropped",
      "The escape `{0}` is read by the shell as a plain '{1}'",
      "Build the byte with `printf`, or write it inside `$'...'`", None,
      Annoying, Policy),
    D(1014, "direct-command-in-test", "test brackets hold a command",
      "Test brackets do not run the command written inside them",
      "Run the command directly as the `if` condition", None, Strict, Policy),
    D(1017, "literal-carriage-return", "the script holds a carriage return",
      "A carriage return in the script text is read as data",
      "Convert the file to Unix line endings with `tr -d '\\r'`", None, Lenient,
      Policy),
    D(1018, "unicode-space", "a Unicode space does not separate words",
      "The Unicode space '{0}' is read by the shell as part of one word",
      "Delete it and retype an ASCII space", None, Strict, Policy),
    D(1019, "missing-unary-operand", "a unary test operator takes one operand",
      "The `{0}` operator expects an operand, and `{1}` is another operator",
      "Give the operator its operand before the comparison", None, Strict,
      Policy),
    D(1026, "brace-group-in-conditional",
      "grouping inside double brackets uses parentheses",
      "A brace does not group a `[[ ]]` expression",
      "Group the expression with `( )`", None, Strict, Policy),
    D(1029, "escaped-conditional-parenthesis",
      "double brackets take unescaped parentheses",
      "A `[[ ]]` expression takes `(` and `)` without a backslash",
      "Remove the backslash before the parenthesis", None, Strict, Policy),
    D(1035, "test-bracket-spacing",
      "test brackets and operands require separating spaces",
      "The bracket and the operand next to it are read as one word",
      "Add spaces after the opening bracket and before the close", None, Strict,
      Policy),
    D(1037, "positional-parameter-braces",
      "a positional parameter above nine needs braces",
      "`$10` expands positional parameter 1 followed by the digit '0'",
      "Write `${10}` to select positional parameter 10", None, Strict, Policy),
    D(1039, "indented-heredoc-terminator",
      "the here-document terminator carries indentation",
      "The indented line holding '{0}' does not close the here-document",
      "Move the terminator to the first column", None, Strict, Policy),
    D(1040, "tab-indented-heredoc-terminator",
      "the here-document terminator carries tab indentation",
      "The tab-indented line holding '{0}' does not close the here-document",
      "Write `<<-` in place of `<<` to strip the leading tabs", None, Strict,
      Policy),
    D(1082, "byte-order-mark", "a byte-order mark precedes the script",
      "A UTF-8 byte-order mark precedes the script text",
      "Save the script as UTF-8 without a byte-order mark", None, Strict,
      Policy),
    D(1084, "swapped-shebang", "the shebang characters are swapped",
      "The first line begins with `!#` and is read as a command",
      "Write `#!` at the start of the line", None, Strict, Policy),
    D(1100, "unicode-dash", "a Unicode dash is not the ASCII minus",
      "The Unicode dash '{0}' is read by the shell as ordinary text",
      "Delete it and retype an ASCII minus", None, Strict, Policy),
    D(1101, "blank-after-continuation",
      "a blank after the backslash breaks the line continuation",
      "A blank follows the backslash, and the line does not continue",
      "Delete the blanks between the backslash and the line ending", None,
      Annoying, Policy),
    D(1104, "shebang-missing-hash", "the shebang is missing its hash",
      "The first line begins with `!` in place of `#!`",
      "Write `#!` at the start of the line", None, Strict, Policy),
    D(1106, "arithmetic-test-operator",
      "arithmetic uses the symbolic comparison operators",
      "Arithmetic reads the `{0}` operator as a subtraction",
      "Use the symbolic form such as `<` or `>` inside arithmetic", None,
      Strict, Policy),
    D(1107, "unknown-shellcheck-directive",
      "the directive names an unknown key",
      "The directive key '{0}' is unknown",
      "Use `disable`, `enable`, `shell`, `source`, `source-path`, or "
      "`external-sources`",
      None, Annoying, Policy),
    D(1109, "html-entity", "an HTML entity is not shell syntax",
      "The HTML entity `&{0};` is read as an operator followed by a command",
      "Write the character the entity names", None, Strict, Policy),
    D(1110, "unicode-quote", "a Unicode quote does not quote anything",
      "The Unicode quote '{0}' opens no quoted string",
      "Delete it and retype an ASCII quote", None, Strict, Policy),
    D(1111, "unicode-quote-in-double-quotes",
      "a Unicode double quote inside a quoted string is literal",
      "The Unicode quote '{0}' inside this double-quoted string is printed as "
      "text",
      "Delete it and retype an ASCII quote, or single-quote the string", None,
      Annoying, Policy),
    D(1112, "unicode-quote-in-single-quotes",
      "a Unicode single quote inside a quoted string is literal",
      "The Unicode quote '{0}' inside this single-quoted string is printed as "
      "text",
      "Delete it and retype an ASCII quote, or double-quote the string", None,
      Annoying, Policy),
    D(1113, "shebang-missing-bang", "the shebang is missing its bang",
      "The first line begins with `#` in place of `#!`",
      "Write `#!` at the start of the line", None, Strict, Policy),
    D(1114, "shebang-leading-space", "whitespace precedes the shebang",
      "The first two bytes of the line are not `#!`",
      "Move `#!` to the start of the line", None, Strict, Policy),
    D(1115, "shebang-inner-space",
      "the shebang holds a space between its characters",
      "The line is read as an ordinary comment",
      "Write `#` and `!` with nothing between them", None, Strict, Policy),
    D(1118, "blank-after-heredoc-terminator",
      "a blank follows the here-document terminator",
      "A blank follows '{0}', and the here-document stays open",
      "Delete the blanks that follow the terminator", None, Strict, Policy),
    D(1123, "directive-before-clause",
      "a directive belongs before a complete command",
      "The word '{0}' continues the command above the directive",
      "Move the directive above the complete command", None, Annoying, Policy),
    D(1124, "directive-before-case-branch",
      "a directive belongs before the `case` command",
      "The directive sits before a case branch",
      "Move the directive above the `case` command", None, Annoying, Policy),
    D(1125, "malformed-shellcheck-directive",
      "a directive takes a key and a value",
      "The directive text '{0}' is not a `key=value` pair",
      "Write the directive as `key=value`, such as `disable=SC2034`", None,
      Annoying, Policy),
    D(1126, "directive-after-command",
      "a directive belongs before the command it covers",
      "The directive follows a command on the same line",
      "Move the directive to its own line above the command", None, Annoying,
      Policy),
    D(1128, "shebang-not-first-line", "the shebang is not on the first line",
      "A shebang is read from the first line only",
      "Move the shebang to the first line", None, Strict, Policy),
    D(1135, "quote-break-for-dollar",
      "the string is closed to keep the dollar sign literal",
      "The double-quoted string is closed right after `$`, and the word "
      "continues after it",
      "Write `\\$` inside the quotes", None, Annoying, Policy),
    D(1143, "continuation-in-comment",
      "a comment does not continue onto the next line",
      "A backslash carries no continuation inside a comment",
      "Move the comment above the command, or wrap it in `` `# ...` ``", None,
      Annoying, Policy),
    D(2000, "echo-piped-into-wc",
      "the shell knows a string length without a pipeline",
      "The `echo` output is counted by `wc` for a length the shell already "
      "knows",
      "Use `${#variable}`", None, Annoying, Policy),
    D(2001, "sed-plain-substitution",
      "the `sed` script is a plain substitution",
      "The `sed` script '{0}' replaces plain text",
      "Use `${variable//search/replace}`", None, Annoying, Policy),
    D(2002, "useless-cat",
      "the `cat` only forwards its file to the next command",
      "The `cat` writes its file unchanged into the pipe",
      "Give the file to the next command directly", None, Annoying, Policy),
    D(2003, "expr-arithmetic",
      "`expr` forks for arithmetic the shell handles directly",
      "The `expr` command forks for a calculation the shell performs in place",
      "Use `$((...))` for the calculation", None, Strict, Policy),
    D(2004, "arithmetic-dollar",
      "arithmetic variables do not need a dollar sign",
      "A dollar sign expands the value before the arithmetic runs",
      "Use the variable name directly inside arithmetic", None, Annoying,
      Policy),
    D(2005, "useless-echo-substitution",
      "`echo` around a command substitution is redundant",
      "An `echo` of a command substitution prints what the command already "
      "prints",
      "Run the command on its own", None, Strict, Policy),
    D(2006, "backticks", "a nested backtick needs a backslash",
      "A backtick inside a backtick must be escaped with a backslash",
      "Use `$(...)` for command substitution", None, Annoying, Policy),
    D(2007, "obsolete-arithmetic-expansion",
      "`$[...]` is the obsolete arithmetic expansion spelling",
      "The `$[...]` spelling is not defined by POSIX",
      "Use `$((...))` for arithmetic expansion", None, Annoying, Policy),
    D(2008, "pipeline-into-echo",
      "a pipeline feeds `echo`, and `echo` reads no stdin",
      "The `echo` command never reads the upstream output",
      "Remove the pipe, or forward the input with `cat`", None, Lenient,
      Policy),
    D(2009, "grep-ps", "grepping `ps` output races the process table",
      "The `grep` matches its own process in the `ps` output",
      "Use `pgrep` to match a process by name", None, Annoying, Policy),
    D(2010, "grep-ls", "grepping `ls` output mangles names",
      "Grepping the `ls` listing mangles a name with a space or a newline",
      "Match the names with a glob or with `find`", None, Lenient, Policy),
    D(2011, "xargs-ls", "piping `ls` into `xargs` mangles names",
      "The `ls` listing splits a name with a space or a newline before `xargs` "
      "reads it",
      "Use `find -print0` with `xargs -0`, or `find -exec`", None, Lenient,
      Policy),
    D(2012, "ls-output-as-data", "the `ls` listing is read as data",
      "The `ls` listing mangles a name with a space or a newline",
      "Use `find`, or match the names with a glob", None, Annoying, Policy),
    D(2013, "for-command-output",
      "a `for` loop over command output iterates words",
      "A `for` loop over the `cat` output iterates IFS-split words",
      "Read the lines with `while IFS= read -r line`", None, Strict, Policy),
    D(2014, "find-exec-substitution",
      "a substitution in the `find` action expands once",
      "The substitution in the `find` action expands once before `find` runs",
      "Move the substitution into `-exec sh -c`", None, Lenient, Policy),
    D(2015, "and-or-else", "`A && B || C` also runs C when B fails",
      "The `C` command runs whenever `A` or `B` fails",
      "Use an `if` statement when C is the else branch", None, Annoying,
      Policy),
    D(2016, "single-quoted-expansion", "single quotes prevent expansion",
      "Single quotes prevent the expansion written inside them",
      "Use double quotes if the value should expand", None, Lenient, Policy),
    D(2017, "integer-division-first",
      "an integer division before a multiplication truncates",
      "The division truncates before the multiplication",
      "Write `a*c/b` to multiply first", None, Annoying, Policy),
    D(2018, "tr-lowercase-range", "the `a-z` range covers ASCII only",
      "The `a-z` range in `tr` leaves an accented letter untranslated",
      "Use `[:lower:]` for the range", None, Annoying, Policy),
    D(2019, "tr-uppercase-range", "the `A-Z` range covers ASCII only",
      "The `A-Z` range in `tr` leaves an accented letter untranslated",
      "Use `[:upper:]` for the range", None, Annoying, Policy),
    D(2020, "tr-word-set", "`tr` translates one character at a time",
      "The `tr` set '{0}' repeats a letter", "Use `sed` to replace a word",
      None, Lenient, Policy),
    D(2021, "tr-bracket-range", "brackets around `tr` ranges add literal bytes",
      "The `[` and `]` are read as members of the `tr` set",
      "Use a quoted range without brackets", None, Annoying, Policy),
    D(2022, "grep-repetition-pattern",
      "the `grep` pattern repeats one character",
      "The star in the regular expression '{0}' repeats the preceding "
      "character",
      "Write `.*` for any text, or match the names with a glob", None, Lenient,
      Policy),
    D(2024, "sudo-glob", "`sudo` does not elevate shell glob expansion",
      "The shell expands this glob before `sudo` changes privileges",
      "Run the glob expansion inside a shell under `sudo`", None, Strict,
      Policy),
    D(2024, "sudo-redirection", "`sudo` does not elevate shell redirections",
      "The shell opens this redirection before `sudo` changes privileges",
      "Run a shell under `sudo` or pipe through `sudo tee`", None, Strict,
      Policy),
    D(2025, "prompt-display-guards",
      "`PS1` control escapes need display guards",
      "The `PS1` value holds a control escape without a `\\[` and `\\]` guard "
      "pair",
      "Wrap nonprinting prompt escapes in `\\[` and `\\]`", None, Annoying,
      Policy),
    D(2028, "echo-escape-sequence",
      "`echo` prints an escape sequence literally",
      "The `echo` operand `{0}` is printed as written",
      "Use `printf` for the escape sequence", None, Lenient, Policy),
    D(2029, "ssh-client-side-expansion",
      "the expansion happens on the client side",
      "The expansion in this `ssh` operand runs on the client before `ssh` "
      "starts",
      "Quote the operand in single quotes", None, Lenient, Policy),
    D(2030, "pipeline-assignment",
      "a pipeline assignment is lost when its stage exits",
      "The assignment runs in the pipeline subshell",
      "Move the assignment outside the pipeline", None, Strict, Policy),
    D(2030, "pipeline-read-assignment",
      "a pipeline read assignment is lost when its stage exits",
      "The `read` runs in the pipeline subshell",
      "Feed the loop with a redirection or process substitution", None, Strict,
      Policy),
    D(2031, "pipeline-later-read",
      "a later read sees the value from before the pipeline",
      "The variable was modified in the pipeline subshell",
      "Move the assignment outside the pipeline", None, Strict, Policy),
    D(2032, "su-runs-no-function", "`su` cannot run a shell function",
      "The shell started by `su` does not define the function '{0}'",
      "Move the body into its own script, or pass it with `sh -c`", None,
      Strict, Policy),
    D(2033, "function-passed-to-command",
      "an external command cannot run a shell function",
      "The function '{0}' is not visible to an external command",
      "Wrap the call in `sh -c`, or move the body into its own script", None,
      Strict, Policy),
    D(2035, "option-shaped-glob",
      "a bare glob can expand to an option-shaped filename",
      "A bare glob can expand to a filename that begins with `-`",
      "Prefix the glob with a directory or place `--` before it", None,
      Annoying, Policy),
    D(2036, "piped-assignment-stage",
      "an assignment feeding a pipe assigns nothing from the pipeline",
      "The assignment to '{0}' runs as the first pipeline stage",
      "Write `{0}=$(...)` around the complete pipeline", None, Strict, Policy),
    D(2037, "assignment-ate-command",
      "an assignment prefix takes the command name",
      "The command name is read as the value of '{0}', and '{1}' becomes the "
      "command",
      "Write `{0}=$(...)` to assign the command output", None, Strict, Policy),
    D(2038, "find-xargs-names",
      "`find` piped to `xargs` breaks on special names",
      "The `xargs` command splits the `find` output on whitespace and quotes",
      "Pair `find -print0` with `xargs -0`, or use `find -exec`", None, Strict,
      Policy),
    D(2043, "for-over-constant-word", "the loop runs once over a constant word",
      "The word list is the one constant word '{0}'",
      "Loop over a glob, a variable, or a command substitution", None, Lenient,
      Policy),
    D(2044, "for-find-output",
      "`for` over `find` output breaks names with whitespace",
      "A `for` loop over the `find` output breaks a name at whitespace",
      "Use `find -exec`, or a `while read -r` loop over `find -print0`", None,
      Strict, Policy),
    D(2045, "for-ls-output", "`for` over `ls` output breaks filenames",
      "A `for` loop over `ls` output breaks filenames at whitespace",
      "Iterate over a glob or read a delimited filename stream", None, Strict,
      Policy),
    D(2046, "unquoted-command-substitution",
      "an unquoted command substitution splits its output",
      "An unquoted command substitution splits its output into words and "
      "expands globs",
      "Quote it to keep one argument", None, Strict, Policy),
    D(2048, "unquoted-star", "`$*` splits positional parameters",
      "`$*` loses the boundaries between positional parameters",
      "Use quoted `\"$@\"` to preserve each argument", None, Strict, Policy),
    D(2049, "regex-operator-takes-glob",
      "the regex operator is given a glob pattern",
      "The `=~` operator takes a regular expression, and '{0}' reads as a glob",
      "Compare with `=` for a glob, or write the pattern as a regex", None,
      Strict, Policy),
    D(2050, "constant-comparison", "a conditional compares two constant values",
      "Both operands of the `{0}` comparison are literal",
      "Remove the constant condition or compare runtime data", None, Annoying,
      Policy),
    D(2051, "variable-brace-range", "brace ranges expand before variables",
      "Brace ranges are expanded before variables",
      "Use an arithmetic loop for a variable limit", None, Lenient, Policy),
    D(2053, "unquoted-conditional-right-operand",
      "an unquoted right operand is matched as a glob",
      "The right side of `{0}` inside `[[ ]]` is matched as a glob",
      "Quote '{1}' so the comparison stays literal", None, Strict, Policy),
    D(2055, "or-between-inequalities",
      "an `||` between two inequalities is always true",
      "The '{0}' operand fails only one of the two `!=` tests",
      "Join the two inequalities with `&&`", None, Strict, Policy),
    D(2056, "test-or-between-inequalities",
      "a test `-o` between two inequalities is always true",
      "The '{0}' operand fails only one of the two `!=` tests",
      "Join the two inequalities with `-a`", None, Strict, Policy),
    D(2057, "unknown-binary-test-operator",
      "the binary slot holds an unknown operator",
      "The `{0}` operator is not a known test operator",
      "Check the operator spelling or quote the operand", None, Strict, Policy),
    D(2058, "unknown-unary-test-operator",
      "the unary slot holds an unknown operator",
      "The `{0}` operator is not a known test operator",
      "Check the operator spelling or quote the operand", None, Strict, Policy),
    D(2059, "variable-printf-format",
      "a variable `printf` format lets the data inject directives",
      "The `printf` format comes from a variable",
      "Use `printf '%s'` to print it", None, Strict, Policy),
    D(2060, "unquoted-tr-range", "an unquoted `tr` range can expand as a glob",
      "The unquoted `tr` range can expand as a filename glob",
      "Quote the range", None, Strict, Policy),
    D(2061, "unquoted-find-pattern",
      "an unquoted `find` pattern expands before `find` sees it",
      "The unquoted `find` pattern is expanded against the working directory "
      "before `find` sees it",
      "Quote the pattern so `find` performs the match", None, Strict, Policy),
    D(2062, "unquoted-grep-pattern",
      "an unquoted `grep` pattern can glob against local files",
      "The unquoted `grep` pattern can glob against the local files before "
      "`grep` sees it",
      "Quote the pattern", None, Strict, Policy),
    D(2063, "grep-glob-pattern", "a `grep` pattern looks like a glob",
      "A leading `*` in a regular expression has nothing to repeat", None, None,
      Lenient, Policy),
    D(2064, "early-trap-expansion",
      "a double-quoted `trap` action expands when it is set",
      "The double-quoted `trap` action expands as the trap is set",
      "Single-quote it so it expands as the signal arrives", None, Lenient,
      Policy),
    D(2065, "test-redirection-comparison",
      "a redirection in a test is not a comparison",
      "The `{0}` is a file redirection",
      "Escape it as `\\>`, or use the `[[ ]]` form", None, Strict, Policy),
    D(2066, "quoted-for-glob", "a quoted for-loop glob stays literal",
      "A quoted for-loop glob remains one literal word",
      "Leave the glob unquoted so it expands into loop values", None, Lenient,
      Policy),
    D(2067, "find-exec-terminator", "`find -exec` needs a terminator",
      "The `find -exec` action has no terminating `;` or `+`",
      "Terminate the action with `\\;` or `+`", None, Strict, Policy),
    D(2068, "unquoted-at", "an unquoted `$@` splits and globs each argument",
      "An unquoted `$@` splits at whitespace and matches each argument as a "
      "glob",
      "Quote it as `\"$@\"`", None, Strict, Policy),
    D(2069, "redirect-order",
      "`2>&1` before a file redirect leaves stderr on the terminal",
      "`2>&1` before the file redirect duplicates the current standard output",
      "Put the file redirect first as in `>file 2>&1`", None, Strict, Policy),
    D(2070, "unquoted-nonempty-test",
      "an unquoted operand breaks the nonempty test",
      "The unquoted `-n` operand vanishes when the value is empty",
      "Quote the operand, or use the `[[ ]]` form", None, Strict, Policy),
    D(2071, "string-numeric-operator",
      "a string operator compares lexicographically",
      "The `{0}` operator compares strings lexicographically",
      "Use an arithmetic command, or a numeric `-lt` or `-gt` operator", None,
      Lenient, Policy),
    D(2072, "decimal-numeric-comparison",
      "a numeric operator compares integers only",
      "The `{0}` operator compares integers, and '{1}' carries a fraction",
      "Compare the decimals with `bc` or `awk`", None, Strict, Policy),
    D(2073, "test-input-redirection", "a `<` in a test redirects input",
      "The `<` reads a file into the test",
      "Escape it as `\\<`, or use the `[[ ]]` form", None, Strict, Policy),
    D(2074, "test-regex-operator",
      "the `test` builtin does not support regex matching",
      "The `test` builtin does not support the `=~` regular expression "
      "operator",
      "Use `[[ value =~ expression ]]`", None, Strict, Policy),
    D(2076, "quoted-regex", "a quoted regular expression is matched literally",
      "A quoted regular expression is matched as literal text",
      "Store the expression in a variable or leave it unquoted", None, Lenient,
      Policy),
    D(2077, "conditional-operator-spacing",
      "a conditional operator needs surrounding spaces",
      "A conditional operator without surrounding spaces is read as part of "
      "one word",
      "Place spaces around the comparison operator", None, Strict, Policy),
    D(2078, "constant-test-operand",
      "a bare literal operand makes the test constant",
      "The '{0}' operand is a literal", "Add the `$` when a variable was meant",
      None, Strict, Policy),
    D(2079, "arithmetic-decimal", "shell arithmetic works on integers only",
      "The decimal '{0}' is a syntax error in shell arithmetic",
      "Compute the value with `bc` or `awk`", None, Strict, Policy),
    D(2080, "octal-literal", "a leading zero selects octal",
      "The literal '{0}' begins with a zero and is read in base eight",
      "Drop the leading zero, or write `10#{0}` for base ten", None, Lenient,
      Policy),
    D(2081, "test-glob-match", "`test` cannot glob-match strings",
      "`[` and `test` compare strings byte for byte and never glob-match",
      "Use a `case`, or the `[[ ]]` form for the pattern", None, Lenient,
      Policy),
    D(2084, "arithmetic-expansion-as-command",
      "the arithmetic result runs as a command",
      "The number produced by the expansion is run as a command",
      "Drop the `$` for `(( ))`, or write `_=$(( ))` to keep the value", None,
      Strict, Policy),
    D(2086, "unquoted-expansion", "an unquoted variable can split and glob",
      "An unquoted variable can split into words and expand globs",
      "Quote the expansion to keep one argument", None, Strict, Policy),
    D(2086, "unquoted-test-expansion",
      "an unquoted test variable can split or vanish",
      "The unquoted test operand vanishes when the value is empty",
      "Quote it to avoid an empty or split argument", None, Strict, Policy),
    D(2087, "unquoted-heredoc-delimiter",
      "an unquoted here document delimiter expands the body on this host",
      "The here document body is expanded on this host before `ssh` sends it",
      "Quote the delimiter to send the body unexpanded", None, Lenient, Policy),
    D(2088, "quoted-tilde", "a quoted tilde remains literal",
      "A quoted tilde stays literal",
      "Leave the tilde unquoted, or use a quoted `$HOME` expansion", None,
      Lenient, Policy),
    D(2089, "quoted-value-assignment", "quotes stored in a value stay literal",
      "The value of '{0}' carries quote bytes",
      "Use an array, or set the positional parameters with `set --`", None,
      Lenient, Policy),
    D(2090, "quoted-value-expansion",
      "an expanded value keeps its quotes literal",
      "The expansion of '{0}' keeps its quote bytes",
      "Use an array, or set the positional parameters with `set --`",
      "'{0}' is assigned here", Lenient, Policy),
    D(2091, "substitution-command-position",
      "a command substitution in command position executes its output",
      "The substitution output is run as a command",
      "Run the command inside the substitution directly", None, Lenient,
      Policy),
    D(2093, "commands-after-exec",
      "commands after `exec` do not run when `exec` succeeds",
      "The `exec` replaces the shell process",
      "Remove the `exec`, or remove the unreachable commands",
      "this is the first command skipped after `exec`", Lenient, Policy),
    D(2094, "read-write-same-file",
      "reading and writing the same file truncates the input",
      "The command reads and truncates '{0}' at once",
      "Write to a temporary file and move it over",
      "this redirect reads the file that is later truncated", Strict, Policy),
    D(2095, "while-read-stdin-consumer",
      "a command in a while-read loop can consume the loop input",
      "An `ssh` command in a while-read loop can consume the loop input",
      "Redirect `ssh` input from `/dev/null`, or pass `-n`", None, Annoying,
      Policy),
    D(2096, "shebang-parameter-count", "a shebang takes at most one parameter",
      "The shebang passes more than one parameter",
      "Keep one parameter and move the options into the script", None, Lenient,
      Policy),
    D(2099, "arithmetic-assignment-expansion",
      "an assignment joins the values as text",
      "The value of '{0}' is joined as text",
      "Write `{0}=$(( ... ))` to evaluate the arithmetic", None, Strict,
      Policy),
    D(2100, "arithmetic-assignment-literal",
      "an assignment stores the expression as text",
      "The value of '{0}' is stored as text",
      "Write `{0}=$(( ... ))` to evaluate the arithmetic", None, Strict,
      Policy),
    D(2103, "directory-change-and-back",
      "a directory change is undone by a later `cd -`",
      "A later `cd -` undoes this directory change",
      "Run the commands inside `( )`", "the working directory is restored here",
      Annoying, Policy),
    D(2104, "break-outside-loop-in-function",
      "a loop control in a function has no loop to leave",
      "The `{0}` command stands in a function outside any loop",
      "Use `return` to leave the function", None, Strict, Policy),
    D(2105, "break-outside-loop", "`break` is valid only inside a loop",
      "The `{0}` command stands outside any loop",
      "Remove it, or move it into the loop it belongs to", None, Strict,
      Policy),
    D(2106, "loop-control-in-pipeline",
      "a loop control inside a pipeline leaves only its own subshell",
      "The `{0}` command leaves the pipeline subshell, and the loop keeps "
      "running",
      "Write `||` in place of the pipe", None, Strict, Policy),
    D(2107, "and-inside-single-bracket", "an `&&` does not join one test",
      "A `[ ]` test does not take `&&`", "Write `[ a ] && [ b ]`", None, Strict,
      Policy),
    D(2108, "conditional-dash-a", "a `[[ ]]` expression takes `&&`",
      "A `[[ ]]` expression joins its parts with `&&`",
      "Write `&&` in place of `-a`", None, Strict, Policy),
    D(2109, "or-inside-single-bracket", "a `||` does not join one test",
      "A `[ ]` test does not take `||`", "Write `[ a ] || [ b ]`", None, Strict,
      Policy),
    D(2110, "conditional-dash-o", "a `[[ ]]` expression takes `||`",
      "A `[[ ]]` expression joins its parts with `||`",
      "Write `||` in place of `-o`", None, Strict, Policy),
    D(2114, "recursive-rm-system-directory",
      "an `rm -r` targets a system directory",
      "An `rm -r` targets the system directory '{0}'",
      "Double-check the path before the command is run", None, Strict, Policy),
    D(2115, "recursive-rm-empty-variable",
      "an `rm -r` can target root when a variable is empty",
      "An `rm -r` on `\"${0}/\"` deletes `/` when the variable is empty",
      "Write `${{0}:?}` so an empty value aborts the command", None, Strict,
      Policy),
    D(2116, "useless-echo-in-substitution",
      "an `echo` in a command substitution is redundant",
      "The `echo` operand is passed through the substitution unchanged",
      "Use the text directly without the command substitution", None, Annoying,
      Policy),
    D(2117, "su-without-command-flag", "`su` takes its command behind `-c`",
      "The operand '{0}' is handed to `su` as a command without `-c`",
      "Write `su -c`, or use `sudo`", None, Lenient, Policy),
    D(2119, "function-call-without-arguments",
      "a call passes no arguments to a function that reads them",
      "The function '{0}' reads arguments, and this call passes none",
      "Pass the values '{0}' expects, or forward `\"$@\"`",
      "the body reads {1} here", Strict, Policy),
    D(2120, "function-arguments-never-passed",
      "a function reads arguments that no call passes",
      "The function '{0}' reads arguments, and no call passes any",
      "Pass the arguments at the call", None, Strict, Policy),
    D(2121, "set-as-assignment", "`set` does not assign a variable",
      "The `set` builtin does not assign '{0}'", "Write `{0}=value` on its own",
      None, Strict, Policy),
    D(2122, "invalid-comparison-operator",
      "the comparison operator does not exist in `test`",
      "The `{0}` operator does not exist in `test`",
      "Negate the opposite comparison, as in `! a < b`", None, Strict, Policy),
    D(2123, "search-path-overwritten",
      "an assignment replaces the command search path",
      "This assignment replaces the command search path with '{0}'",
      "Name the variable something else, or keep `$PATH` in the value", None,
      Lenient, Policy),
    D(2124, "scalar-at-assignment",
      "a scalar assignment from `$@` loses boundaries",
      "A scalar assignment from `$@` joins every argument into one string",
      "Assign one value, or use an array", None, Lenient, Policy),
    D(2125, "literal-glob-assignment",
      "a glob in an assignment value stays literal",
      "The value of '{0}' keeps the pattern as text",
      "Quote the value when the pattern is data, or use an array", None,
      Lenient, Policy),
    D(2126, "grep-wc-count", "a `wc -l` on `grep` output runs an extra process",
      "The `grep` output is piped into `wc -l` for a count `grep` performs on "
      "its own",
      "Use `grep -c` to count the matching lines directly", None, Annoying,
      Policy),
    D(2128, "array-without-subscript",
      "an array without a subscript expands to one element",
      "The expansion of '{0}' without a subscript reads the first element "
      "alone",
      "Write `${{0}[@]}` to expand every element", None, Strict, Policy),
    D(2129, "repeated-append", "several appends can share one redirection",
      "Several commands append to the same file separately",
      "Apply one append redirection to a grouped command",
      "this later append belongs under the same redirection", Annoying, Policy),
    D(2130, "integer-comparison-on-text",
      "the `-eq` operator compares integers only",
      "The `-eq` operator compares integers, and '{0}' is not an integer",
      "Use `=` to compare the text", None, Strict, Policy),
    D(2140, "quote-sandwich", "a bare word sits between two quoted runs",
      "The word closes a quote, leaves '{0}' bare, and opens a quote again",
      "Quote the complete word, or escape the inner quotes", None, Lenient,
      Policy),
    D(2141, "literal-escape-separator",
      "an escape written as text stays two bytes",
      "The value of '{0}' carries a backslash and a letter",
      "Write `$'\\t'` to place the control byte", None, Lenient, Policy),
    D(2142, "alias-positional-arguments",
      "an alias body cannot receive positional arguments",
      "The `$1` in an alias body reads the positional arguments of the "
      "surrounding script",
      "Use a function when the wrapper needs arguments", None, Annoying,
      Policy),
    D(2143, "tested-grep-output", "the `grep` output is tested for a match",
      "The complete `grep` output is collected to learn whether one line "
      "matched",
      "Use `grep -q` and test its exit status", None, Lenient, Policy),
    D(2144, "glob-file-test", "a file test on a glob checks one expanded path",
      "A file test on a glob checks only one expanded path",
      "Expand the glob in a loop and test each path", None, Strict, Policy),
    D(2145, "at-inside-word", "`$@` inside a longer word concatenates text",
      "`$@` inside a longer word concatenates the surrounding text onto the "
      "first and last argument",
      "Use `$*` for one joined string, or a separate `\"$@\"` word", None,
      Strict, Policy),
    D(2146, "find-or-grouping", "`find` actions after `-o` need grouping",
      "The `find` expression uses `-o` without grouping its actions",
      "Group each side with escaped parentheses", None, Lenient, Policy),
    D(2147, "literal-tilde-path", "a tilde inside `PATH` remains literal",
      "A tilde inside `PATH` is not expanded",
      "Expand `HOME` before assigning `PATH`", None, Lenient, Policy),
    D(2148, "missing-shebang", "the script names no interpreter",
      "The analysis cannot tell which shell the script targets",
      "Add a shebang such as `#!/bin/sh` on the first line", None, Annoying,
      Policy),
    D(2151, "return-extra-operands", "`return` takes one status",
      "The `return` builtin takes one number from 0 to 255",
      "Write the other data to standard output", None, Strict, Policy),
    D(2152, "return-substitution-value", "`return` takes a status number",
      "The `return` operand is command output",
      "Print the value and return a status separately", None, Strict, Policy),
    D(2153, "misspelled-variable-name",
      "a read name resembles an assigned name",
      "The variable '{0}' is never assigned, and '{1}' is assigned",
      "Correct the spelling or assign '{0}'", "{2}", Strict, Policy),
    D(2153, "misspelled-builtin-variable-name",
      "a read name resembles a shell-maintained name",
      "The variable '{0}' is never assigned, and the shell provides '{1}'",
      "Correct the spelling or assign '{0}'", None, Strict, Policy),
    D(2154, "unassigned-variable-read",
      "a name is read that the script never assigns",
      "The variable '{0}' is read before any assignment gives it a value",
      "Assign '{0}' before it is read, or set it in the environment", None,
      Strict, Policy),
    D(2155, "declare-substitution-status",
      "a `declare` and an assignment can mask command status",
      "Declaring and assigning from a command substitution in one command "
      "masks the command's exit status",
      "Split the declaration and the assignment so a failure is seen", None,
      Lenient, Policy),
    D(2156, "find-exec-source-injection",
      "`find -exec` shell text must receive filenames as arguments",
      "The `find` result is inserted into shell source and can execute "
      "filename text",
      "Pass the result as an argument and reference it as `$1`", None, Strict,
      Policy),
    D(2157, "literal-string-test",
      "a literal string test operand makes the test constant",
      "The string test has a literal operand",
      "Test a variable or drop the check", None, Annoying, Policy),
    D(2157, "literal-test", "a literal test operand makes the test constant",
      "The `{0}` test has a literal operand",
      "Test a variable or drop the check", None, Annoying, Policy),
    D(2158, "bracketed-false",
      "the brackets around `false` invert what the word means",
      "`[ false ]` tests the nonempty word `false`",
      "Drop the brackets and write `false`", None, Strict, Policy),
    D(2159, "bracketed-zero",
      "the brackets around `0` invert what the digit means",
      "`[ 0 ]` tests the nonempty word `0`",
      "Write `false` for a failing condition", None, Strict, Policy),
    D(2160, "bracketed-true", "the brackets around `true` add nothing",
      "`[ true ]` tests the nonempty word `true`",
      "Drop the brackets and write `true`", None, Annoying, Policy),
    D(2161, "bracketed-one", "the brackets around `1` add nothing",
      "`[ 1 ]` tests the nonempty word `1`",
      "Write `true` for a succeeding condition", None, Annoying, Policy),
    D(2162, "read-without-r", "a `read` without `-r` mangles backslashes",
      "A `read` without `-r` treats a backslash in the input as an escape",
      "Add `-r` to read the line literally", None, Lenient, Policy),
    D(2163, "export-expanded-name", "`export` takes a name",
      "The `export` operand expands '{0}'",
      "Drop the dollar sign to export '{0}' itself", None, Strict, Policy),
    D(2164, "unchecked-cd",
      "an unchecked `cd` can leave commands in the wrong directory",
      "This `cd` is unchecked", "Stop or return when `cd` fails", None,
      Annoying, Policy),
    D(2165, "nested-loop-reuse", "a nested loop reuses the outer variable",
      "The inner loop reuses the outer loop variable '{0}'",
      "Use a distinct variable for the nested loop",
      "the outer loop first binds '{0}' here", Annoying, Policy),
    D(2166, "obsolescent-test-and-or",
      "a `test` with `-a` or `-o` is obsolescent",
      "The `-a` and `-o` operators are marked obsolescent by POSIX",
      "Join two tests with `&&` or `||`", None, Annoying, Policy),
    D(2167, "nested-loop-overwrite",
      "a nested loop overwrites the outer variable",
      "The outer loop variable '{0}' is overwritten by the inner loop",
      "Use a distinct variable for the nested loop",
      "the inner loop binds '{0}' again here", Annoying, Policy),
    D(2168, "local-outside-function", "`local` outside a function has no scope",
      "A `local` outside a function has no scope to bind",
      "Declare the variable plainly, or move it into a function", None, Strict,
      Policy),
    D(2170, "non-numeric-test-operand",
      "a numeric test operator has a non-numeric literal",
      "The numeric comparison `{0}` reads '{1}', and that is not a number",
      None, None, Strict, Policy),
    D(2171, "unmatched-closing-bracket",
      "a trailing bracket sits outside a test",
      "The trailing `]` has no opening `[`",
      "Add the opening `[`, or quote the bracket when it is data", None,
      Lenient, Policy),
    D(2172, "trap-signal-number", "a trapped signal is named by its number",
      "The trap condition '{0}' is a signal number",
      "Name the signal, such as `INT` or `TERM`", None, Lenient, Policy),
    D(2173, "trap-unblockable-signal",
      "the `KILL` and `STOP` signals cannot be trapped",
      "The signal '{0}' cannot be trapped", "Remove the condition", None,
      Strict, Policy),
    D(2174, "mkdir-parent-mode",
      "a `mkdir -pm` applies the mode only to the deepest directory",
      "The created parent directories keep the umask default", None, None,
      Lenient, Policy),
    D(2176, "posix-timed-pipeline",
      "timing a pipeline is undefined in POSIX sh",
      "The `time` keyword times only a simple command in POSIX sh",
      "Time one stage, or run the pipeline through `sh -c` and time that", None,
      Strict, Policy),
    D(2177, "posix-timed-compound",
      "timing a compound command is undefined in POSIX sh",
      "The `time` keyword times only a simple command in POSIX sh",
      "Run the compound command through `sh -c` and time that", None, Strict,
      Policy),
    D(2178, "array-assigned-string", "an array name is reassigned as a scalar",
      "This assignment replaces the array '{0}' with one string in the first "
      "element",
      "Write `{0}=( ... )` to keep the array", None, Strict, Policy),
    D(2179, "array-appended-string",
      "a scalar append on an array name changes the first element",
      "A scalar append on the array '{0}' changes the first element",
      "Write `{0}+=( ... )` to append an element", None, Strict, Policy),
    D(2180, "multidimensional-array", "a shell array has one dimension",
      "The name '{0}' carries several subscripts",
      "Flatten the index, or use an associative array", None, Strict, Policy),
    D(2181, "indirect-exit-status-test", "a test of `$?` is indirect",
      "Testing `$?` checks the exit status indirectly",
      "Test the command directly with `if` or `&&`", None, Annoying, Policy),
    D(2182, "printf-ignored-arguments",
      "the `printf` format consumes no arguments",
      "The remaining `printf` operands are ignored",
      "Add a format directive, or remove the extra operands", None, Lenient,
      Policy),
    D(2183, "printf-missing-arguments",
      "`printf` has fewer arguments than its format consumes",
      "The `printf` format consumes more arguments than the command supplies",
      "Add the missing arguments, or remove format directives", None, Lenient,
      Policy),
    D(2184, "unquoted-unset-index",
      "an unquoted unset array index can expand as a glob",
      "An unquoted unset array index can expand as a filename glob",
      "Quote the complete array element name", None, Strict, Policy),
    D(2185, "find-without-path", "`find` is given no path to search",
      "Some `find` implementations have no default path",
      "Write `.` as the path before the expression", None, Lenient, Policy),
    D(2188, "redirection-without-command", "a redirection has no command",
      "The redirection is attached to no command",
      "Attach the redirection to its command, or write `: > file`", None,
      Lenient, Policy),
    D(2189, "pipeline-stage-without-command", "a pipeline stage has no command",
      "The pipeline stage holds a redirection and no command",
      "Attach the redirection to the command that reads it", None, Strict,
      Policy),
    D(2193, "impossible-comparison", "the compared literals can never be equal",
      "The literals '{0}' and '{1}' differ",
      "Compare a variable, or correct the operand spelling", None, Strict,
      Policy),
    D(2194, "constant-case-word", "the `case` word is constant",
      "The `case` word '{0}' is constant",
      "Add the missing `$`, or drop the `case`", None, Lenient, Policy),
    D(2195, "unmatchable-case-pattern",
      "the pattern never matches the `case` word",
      "The pattern '{0}' cannot match the `case` word '{1}'",
      "Correct the pattern or the `case` word", None, Strict, Policy),
    D(2196, "deprecated-egrep", "`egrep` is deprecated",
      "The `egrep` command is deprecated",
      "Use `grep -E` for the extended regular expression match", None, Annoying,
      Policy),
    D(2197, "deprecated-fgrep", "`fgrep` is deprecated",
      "The `fgrep` command is deprecated",
      "Use `grep -F` for the fixed string match", None, Annoying, Policy),
    D(2198, "array-operand-in-test", "an array does not fit one test operand",
      "The `[ ]` test takes one word per operand, and '{0}' expands to every "
      "element",
      "Loop over the elements, or join them with `*`", None, Strict, Policy),
    D(2199, "array-operand-in-conditional",
      "an array concatenates inside double brackets",
      "A `[[ ]]` expression concatenates '{0}' into one word",
      "Loop over the elements, or write `*` in place of `@`", None, Strict,
      Policy),
    D(2200, "brace-expansion-in-test",
      "a brace expansion does not fit one test operand",
      "The `[ ]` test takes one word per operand, and '{0}' expands to several",
      "Loop over the expanded words", None, Strict, Policy),
    D(2201, "brace-expansion-in-conditional",
      "a brace expansion stays literal inside double brackets",
      "A `[[ ]]` expression leaves '{0}' unexpanded",
      "Loop over the expanded words", None, Strict, Policy),
    D(2202, "glob-operand-in-test", "a glob does not fit one test operand",
      "The `[ ]` test takes one word per operand, and '{0}' expands to every "
      "match",
      "Loop over the matches", None, Strict, Policy),
    D(2203, "glob-operand-in-conditional",
      "a glob stays literal inside double brackets",
      "The glob '{0}' stays literal inside a `[[ ]]` expression",
      "Loop over the matches", None, Strict, Policy),
    D(2204, "parentheses-subshell", "parentheses start a subshell",
      "A subshell performs no file or string test",
      "Use `[[ ... ]]` or `[ ... ]` for the condition", None, Strict, Policy),
    D(2205, "subshell-as-condition", "a subshell is not a test expression",
      "A `( )` subshell runs its contents", "Write the condition as `[ ... ]`",
      None, Strict, Policy),
    D(2206, "array-element-splitting",
      "an unquoted element splits into several array entries",
      "The expansion in this array element splits on whitespace and expands "
      "globs",
      "Quote the element, or split the value with `mapfile` or `read -a`", None,
      Lenient, Policy),
    D(2207, "array-from-command-output",
      "an array from command output splits and globs",
      "An array built from command output splits words and expands globs",
      "Use `mapfile` or `readarray` to preserve output records", None, Strict,
      Policy),
    D(2208, "unquoted-set-variable-operand",
      "the `-v` operand expands as a glob",
      "The `-v` operand '{0}' carries glob characters",
      "Quote the name, or use the `[[ ]]` form", None, Strict, Policy),
    D(2209, "command-name-as-value", "an assigned command name stores the name",
      "The value of '{0}' is the command name '{1}'",
      "Write `{0}=$({1})` to store its output, or quote the name", None,
      Lenient, Policy),
    D(2210, "numeric-redirection-target",
      "a redirection target of digits is not a descriptor",
      "The redirect writes to the file named '{0}'",
      "Write `>&{0}` to reach the descriptor, or compare the numbers in a test",
      None, Lenient, Policy),
    D(2212, "empty-test", "an empty test always fails",
      "A test with no operand always fails",
      "Write `false` for a failing condition", None, Strict, Policy),
    D(2213, "getopts-option-unhandled",
      "a declared option reaches no case branch",
      "The optstring declares '{0}', and no branch of this `case` handles it",
      "Add a `{0})` branch, or drop the letter from the optstring",
      "this optstring declares the option", Lenient, Policy),
    D(2214, "case-branch-outside-optstring",
      "a case branch names an option the optstring omits",
      "The optstring does not declare '{0}'",
      "Add the letter to the optstring, or remove the branch",
      "this optstring omits the option", Lenient, Policy),
    D(2215, "option-command-position", "an option-shaped word is not a command",
      "An option-shaped word in command position is looked up as a command "
      "name",
      "Place the option after its command", None, Strict, Policy),
    D(2216, "pipeline-non-reader",
      "a pipeline feeds a command that ignores stdin",
      "The '{0}' command never reads the upstream output", None, None, Lenient,
      Policy),
    D(2217, "redirect-non-reader",
      "an input redirect feeds a command that ignores stdin",
      "The '{0}' command never reads the redirected input", None, None,
      Annoying, Policy),
    D(2218, "function-called-before-definition",
      "a call runs before the function is defined",
      "The definition of '{0}' runs later in the file",
      "Move the definition of '{0}' above this call",
      "the definition runs after the call", Strict, Policy),
    D(2219, "let-arithmetic-command", "a `let` command evaluates arithmetic",
      "The `let` builtin evaluates its argument as arithmetic",
      "Write `(( ... ))` for the arithmetic", None, Annoying, Policy),
    D(2220, "getopts-invalid-option-unhandled",
      "an invalid option reaches no case branch",
      "`getopts` stores a question mark for an unknown option, and no branch "
      "handles it",
      "Add a `*)` branch that prints the usage and exits",
      "this loop reads the options", Annoying, Policy),
    D(2221, "duplicate-case-pattern",
      "an earlier `case` pattern makes this pattern unreachable",
      "An earlier `case` pattern matches everything this pattern matches",
      "Remove the duplicate pattern", "this identical pattern matches first",
      Strict, Policy),
    D(2222, "shadowed-case-pattern",
      "an earlier `case` pattern shadows this pattern",
      "An earlier `case` pattern is broader",
      "Move the specific pattern before the broader pattern",
      "this broader pattern shadows the later pattern", Annoying, Policy),
    D(2223, "unquoted-default-assignment",
      "an unquoted default assignment is split and globbed",
      "The default value given to '{0}' is split into words and matched "
      "against "
      "the filenames",
      "Quote the expansion to keep the default intact", None, Annoying, Policy),
    D(2224, "move-without-destination", "the move has no destination",
      "The `mv` command is given '{0}' alone", "Add the destination path", None,
      Strict, Policy),
    D(2225, "copy-without-destination", "the copy has no destination",
      "The `cp` command is given '{0}' alone", "Add the destination path", None,
      Strict, Policy),
    D(2226, "link-without-destination", "the link has no destination",
      "The `ln` command is given '{0}' alone",
      "Add the link name, or write `.` explicitly", None, Strict, Policy),
    D(2229, "read-variable-dollar",
      "`read` expects a variable name without a dollar sign",
      "The `read` operand carries a dollar sign",
      "Drop the dollar sign from the variable name", None, Strict, Policy),
    D(2230, "which-is-nonstandard", "`which` is not a shell builtin",
      "The `which` program is not standard and is missing on some systems",
      "Use `command -v` to look up the name", None, Annoying, Policy),
    D(2231, "unquoted-expansion-in-glob",
      "an unquoted expansion beside a glob splits on whitespace",
      "The expansion in '{0}' is unquoted",
      "Quote the expansion and leave the glob characters outside the quotes",
      None, Annoying, Policy),
    D(2232, "sudo-runs-no-builtin", "`sudo` cannot run a shell builtin",
      "The builtin '{0}' is not found by `sudo`",
      "Wrap the builtin in `sudo sh -c`", None, Strict, Policy),
    D(2233, "redundant-condition-parentheses",
      "the parentheses around the condition add nothing",
      "The `( )` around the condition starts a subshell and changes nothing "
      "else",
      "Remove the parentheses", None, Annoying, Policy),
    D(2234, "redundant-test-parentheses",
      "the parentheses around the test add nothing",
      "The `( )` around the test starts a subshell and changes nothing else",
      "Remove the parentheses", None, Annoying, Policy),
    D(2235, "subshell-grouping",
      "a subshell groups what braces group in the current shell",
      "The `( )` group starts a subshell and costs a process on every run",
      "Write `{ ...; }` to group the commands in the current shell", None,
      Annoying, Policy),
    D(2236, "negated-z", "a negated `-z` is `-n`", "A negated `-z` is `-n`",
      "Test with `-n`", None, Annoying, Policy),
    D(2237, "negated-n", "a negated `-n` is `-z`", "A negated `-n` is `-z`",
      "Test with `-z`", None, Annoying, Policy),
    D(2238, "redirection-to-command-name",
      "a redirection target names a command",
      "The redirect opens a file named '{0}', and the command never runs",
      "Feed `{0}` through a pipe, or quote the name to write the file", None,
      Strict, Policy),
    D(2239, "shebang-relative-interpreter", "the shebang names a relative path",
      "The shebang names '{0}', and that path is not absolute",
      "Write an absolute path, or use `#!/usr/bin/env` to search `PATH`", None,
      Strict, Policy),
    D(2240, "posix-dot-arguments", "the POSIX dot command takes no argument",
      "The POSIX `.` command takes no argument, and '{0}' never reaches it",
      "Set the values as variables before the file is read", None, Strict,
      Policy),
    D(2241, "exit-extra-operands", "`exit` takes one status",
      "The `exit` builtin takes one number from 0 to 255",
      "Write the other data to standard output", None, Strict, Policy),
    D(2242, "invalid-status-code",
      "an `exit` or `return` code is outside 0 through 255",
      "The code '{0}' is not a number from 0 to 255, and `{1}` either rejects "
      "it or wraps it modulo 256",
      None, None, Lenient, Policy),
    D(2243, "one-operand-output-test",
      "a one-operand test on output checks for printed bytes",
      "A one-operand test on command output only checks that something was "
      "printed",
      "Write it with `-n`, or drop the brackets to check the exit status", None,
      Annoying, Policy),
    D(2244, "one-operand-test", "a one-operand test is a nonempty-string test",
      "A one-operand test is the nonempty-string test", "Write it with `-n`",
      None, Annoying, Policy),
    D(2245, "file-test-on-glob-in-test",
      "a file test reaches only the first expanded path",
      "The `{0}` test runs against the first path '{1}' expands to",
      "Loop over the matches to test each one", None, Lenient, Policy),
    D(2246, "shebang-directory-interpreter", "the shebang names a directory",
      "The shebang names '{0}', and that path ends in a slash",
      "Remove the trailing slash", None, Strict, Policy),
    D(2249, "case-without-default", "a `case` without a default can miss input",
      "This `case` has no default `*)` branch", None, None, Annoying, Policy),
    D(2251, "negation-skips-errexit",
      "a negated command is not a condition and skips errexit",
      "The `!` inhibits errexit whether the command succeeds or fails, and "
      "nothing reads the status",
      "Write `|| exit 1` after it, or check `$?`", None, Lenient, Policy),
    D(2252, "or-between-bracket-inequalities",
      "an or between two bracketed inequalities is always true",
      "The '{0}' operand fails only one of the two `!=` tests",
      "Join the two tests with `&&`", None, Strict, Policy),
    D(2254, "unquoted-case-pattern",
      "an unquoted expansion in a case pattern matches as a glob",
      "The expansion in the pattern '{0}' is matched as a glob",
      "Quote the expansion so the pattern matches literally", None, Lenient,
      Policy),
    D(2255, "test-arithmetic-operand",
      "test brackets do not evaluate arithmetic",
      "Test brackets compare '{0}' as text, and the arithmetic is not "
      "evaluated",
      "Evaluate the numbers with `$((...))` before the comparison", None,
      Lenient, Policy),
    D(2257, "redirection-mutation", "redirection expansion can lose mutation",
      "A redirection expansion can run in a child and lose its mutation",
      "Update the variable before forming the redirect path", None, Strict,
      Policy),
    D(2259, "redirection-overrides-input-pipe",
      "a redirection overrides the piped input",
      "The input redirection closes the pipe into '{0}'",
      "Pass the file as an operand, or merge the inputs into one stream", None,
      Strict, Policy),
    D(2260, "redirection-overrides-output-pipe",
      "a redirection overrides the piped output",
      "The output redirection closes the pipe out of '{0}'",
      "Use `tee` to write the file and feed the pipe", None, Strict, Policy),
    D(2261, "competing-redirections",
      "several redirections compete for one descriptor",
      "The redirect to '{0}' competes with an earlier redirect for the same "
      "descriptor",
      "Pass the files as operands, or use `tee` for several outputs",
      "this earlier redirect claims the same descriptor", Strict, Policy),
    D(2264, "recursive-wrapper", "a function wrapper calls itself recursively",
      "The '{0}' function calls itself",
      "Use `command` before the wrapped command name", "'{0}' is defined here",
      Strict, Policy),
    D(2267, "deprecated-xargs-replace", "the `xargs -i` flag is deprecated",
      "The `xargs -i` flag is deprecated",
      "Use `-I` with an explicit replacement string", None, Annoying, Policy),
    D(2268, "x-prefix-test", "the x-prefix test workaround is obsolete",
      "The x-prefix test workaround is obsolete", "Quote the variable directly",
      None, Annoying, Policy),
    D(2269, "self-assignment", "a variable is assigned its own value",
      "The value assigned to '{0}' is the value '{0}' already holds",
      "Remove the assignment, or name the variable that the value comes from",
      None, Lenient, Policy),
    D(2270, "positional-assignment-name",
      "a positional parameter cannot be assigned",
      "A positional parameter cannot be assigned, and '{0}' runs as a command",
      "Assign to a named variable, or compare with `[ x = y ]`", None, Strict,
      Policy),
    D(2271, "expanded-assignment-name",
      "an assignment name cannot come from an expansion",
      "An assignment name cannot come from an expansion, and '{0}' runs as a "
      "command",
      "Use an array, or assign through `read`", None, Strict, Policy),
    D(2272, "equals-in-command-name", "a command name carries a double equals",
      "The word '{0}' holds `==` and runs as a command name",
      "Write `[ x = y ]` to compare the values", None, Strict, Policy),
    D(2273, "triple-equals-run", "a run of equals signs runs as a command",
      "The word '{0}' is a run of equals signs and runs as a command name",
      "Remove the separator line, or comment it out", None, Strict, Policy),
    D(2274, "command-name-starts-triple-equals",
      "a command name starts with a run of equals signs",
      "The word '{0}' starts with `===` and is neither an assignment nor a "
      "comparison",
      "Write `[ x = y ]` to compare the values", None, Strict, Policy),
    D(2275, "command-name-starts-equals", "a command name starts with equals",
      "An assignment needs a name before the equals sign, and '{0}' runs as a "
      "command",
      "Add the variable name before the equals sign", None, Strict, Policy),
    D(2276, "quoted-assignment-name", "a quoted assignment name is a command",
      "The quotes make '{0}' one command name, and no assignment is performed",
      "Remove the quotes to assign, or write `[ x = y ]` to compare", None,
      Strict, Policy),
    D(2277, "positional-zero-assignment",
      "the zeroth positional parameter cannot be assigned",
      "The `$0` parameter cannot be assigned, and '{0}' runs as a command",
      "Assign to `BASH_ARGV0`", None, Strict, Policy),
    D(2279, "positional-zero-assignment-posix",
      "the zeroth positional parameter cannot be assigned in POSIX sh",
      "The `$0` parameter cannot be assigned in POSIX sh, and '{0}' runs as a "
      "command",
      "Assign the program name to a named variable", None, Strict, Policy),
    D(2281, "dollar-assignment-name",
      "an assignment name must not start with a dollar sign",
      "An assignment name must not start with a dollar sign",
      "Remove the dollar sign from the assignment name", None, Strict, Policy),
    D(2282, "numeric-assignment-name",
      "a variable name cannot start with a digit",
      "A variable name cannot start with a digit, and '{0}' runs as a command",
      "Rename the variable to start with a letter or an underscore", None,
      Strict, Policy),
    D(2283, "assignment-equals-spacing",
      "an assignment cannot contain spaces around equals",
      "An assignment with spaces around equals is read as a command and its "
      "arguments",
      "Write `NAME=value` without spaces", None, Strict, Policy),
    D(2284, "comparison-as-command",
      "a comparison written as a command runs the left operand",
      "The `==` comparison runs '{0}' as a command",
      "Write `[ x = y ]` to compare the values", None, Strict, Policy),
    D(2285, "append-equals-spacing",
      "an append cannot contain spaces around the operator",
      "An append cannot contain spaces around `+=`, and '{0}' runs as a "
      "command",
      "Write `NAME+=value` without spaces", None, Strict, Policy),
    D(2335, "negated-numeric-comparison",
      "a negated numeric comparison has a direct operator",
      "A negated `{0}` is `{1}`", "Drop the `!` and use `{1}`", None, Annoying,
      Policy),
    D(3001, "posix-process-substitution",
      "process substitution is absent from POSIX sh",
      "The `<(...)` process substitution is a bash extension absent from POSIX "
      "sh",
      "Use a named pipe or a temporary file under a `sh` shebang", None, Strict,
      Policy),
    D(3002, "posix-extglob", "extended globs are absent from POSIX sh",
      "The extended glob `{0}` is a bash extension absent from POSIX sh",
      "Use a `case` statement or a plain glob under a `sh` shebang", None,
      Strict, Policy),
    D(3003, "posix-ansi-c-quoting", "`$'...'` quoting is absent from POSIX sh",
      "The `$'...'` quoting form is a bash extension absent from POSIX sh",
      "Use `printf` to produce the escapes under a `sh` shebang", None, Strict,
      Policy),
    D(3004, "posix-locale-quoting",
      "`$\"...\"` quoting is absent from POSIX sh",
      "The `$\"...\"` quoting form is a bash extension absent from POSIX sh",
      "Use ordinary double quotes under a `sh` shebang", None, Strict, Policy),
    D(3006, "posix-standalone-arithmetic",
      "a standalone `((...))` is undefined in POSIX sh",
      "The standalone `((...))` command is a bash extension absent from POSIX "
      "sh",
      "Use the `: $((...))` form under a `sh` shebang", None, Strict, Policy),
    D(3012, "posix-test-lexicographical",
      "a lexicographical comparison is undefined in POSIX test",
      "The `{0}` comparison in `test` is undefined in POSIX sh",
      "Compare with `expr` or a `case` statement under a `sh` shebang", None,
      Strict, Policy),
    D(3013, "posix-test-file-comparison",
      "a file comparison operator is undefined in POSIX test",
      "The `{0}` operator in `test` is undefined in POSIX sh",
      "Compare the timestamps with `find` or `ls` under a `sh` shebang", None,
      Strict, Policy),
    D(3014, "posix-test-equals", "`==` is undefined in POSIX test",
      "`==` is undefined in POSIX `test`", "Use `=` for string equality", None,
      Strict, Policy),
    D(3017, "posix-test-unary-a", "a unary `-a` is undefined in POSIX test",
      "The unary `-a` in `test` is undefined in POSIX sh",
      "Use `-e` for the file test", None, Strict, Policy),
    D(3018, "posix-arithmetic-increment",
      "the increment operators are undefined in POSIX sh",
      "The `{0}` operator in arithmetic is undefined in POSIX sh",
      "Write the assignment out under a `sh` shebang", None, Strict, Policy),
    D(3019, "posix-arithmetic-exponent",
      "the exponent operator is undefined in POSIX sh",
      "The `**` operator in arithmetic is undefined in POSIX sh",
      "Multiply the value out under a `sh` shebang", None, Strict, Policy),
    D(3020, "posix-both-streams-redirect",
      "the `&>` redirection is absent from POSIX sh",
      "The `&>` redirection is a bash extension absent from POSIX sh",
      "Write the file redirect and `2>&1` separately under a `sh` shebang",
      None, Strict, Policy),
    D(3021, "posix-dup-to-filename",
      "a `>&` with a filename is absent from POSIX sh",
      "The `>&` redirection to '{0}' is a bash extension absent from POSIX sh",
      "Write the file redirect and `2>&1` separately under a `sh` shebang",
      None, Strict, Policy),
    D(3022, "posix-named-descriptor",
      "a named file descriptor is absent from POSIX sh",
      "The named file descriptor '{0}' is a bash extension absent from POSIX "
      "sh",
      "Name a fixed descriptor number under a `sh` shebang", None, Strict,
      Policy),
    D(3023, "posix-descriptor-range",
      "a file descriptor above nine is undefined in POSIX sh",
      "The file descriptor '{0}' is outside the range POSIX sh defines",
      "Use a descriptor from 0 to 9 under a `sh` shebang", None, Strict,
      Policy),
    D(3024, "posix-append-assignment",
      "the `+=` assignment is absent from POSIX sh",
      "The `+=` assignment to '{0}' is a bash extension absent from POSIX sh",
      "Write `NAME=\"$NAME\"value` under a `sh` shebang", None, Strict, Policy),
    D(3025, "posix-network-device",
      "the network devices are absent from POSIX sh",
      "The path '{0}' is a bash network device that POSIX sh leaves undefined",
      "Open the connection with a network client under a `sh` shebang", None,
      Strict, Policy),
    D(3026, "posix-glob-caret",
      "a `^` in a bracket expression is not a POSIX negation",
      "A `^` opens the bracket expression `{0}`, and POSIX sh negates with `!`",
      "Use `[! ...]` under a `sh` shebang", None, Strict, Policy),
    D(3028, "posix-bash-variable",
      "the variable is defined by bash and not by POSIX sh",
      "'{0}' is a bash variable that POSIX sh leaves undefined",
      "Compute the value another way under a `sh` shebang", None, Strict,
      Policy),
    D(3030, "posix-array-reader",
      "`mapfile` and `readarray` are absent from POSIX sh",
      "'{0}' is a bash array builtin absent from POSIX sh",
      "Read the input with a `while read` loop, or switch the shebang to bash",
      None, Strict, Policy),
    D(3031, "posix-glob-redirect",
      "a glob redirection target is undefined in POSIX sh",
      "The redirection target '{0}' is a glob that POSIX sh leaves undefined",
      "Name the file explicitly under a `sh` shebang", None, Strict, Policy),
    D(3034, "posix-file-substitution", "`$(<file)` is absent from POSIX sh",
      "The `$(<file)` form is a bash shorthand absent from POSIX sh",
      "Use `$(cat file)` under a `sh` shebang", None, Strict, Policy),
    D(3035, "posix-backtick-file-substitution",
      "a backtick file substitution is absent from POSIX sh",
      "The `` `<file` `` form is a bash shorthand absent from POSIX sh",
      "Use `$(cat file)` under a `sh` shebang", None, Strict, Policy),
    D(3037, "posix-echo-flag", "the `echo` flags are not in POSIX echo",
      "An `echo {0}` relies on a bash builtin, and the POSIX `echo` prints the "
      "flag as text",
      "Use `printf` under a `sh` shebang", None, Strict, Policy),
    D(3038, "posix-exec-flag", "exec flags are absent from POSIX sh",
      "The `exec` `{0}` flag is a bash extension absent from POSIX sh",
      "Drop the flag under a `sh` shebang", None, Strict, Policy),
    D(3039, "posix-let", "`let` is absent from POSIX sh",
      "The `let` builtin is a bash extension absent from POSIX sh",
      "Use the `: $((...))` form under a `sh` shebang", None, Strict, Policy),
    D(3043, "posix-local", "`local` is absent from POSIX sh",
      "The `local` builtin is not in POSIX sh",
      "Rework the function, or switch the shebang to bash", None, Strict,
      Policy),
    D(3044, "posix-declare", "`declare` is absent from POSIX sh",
      "The `{0}` builtin is not in POSIX",
      "Assign the variable plainly under a `sh` shebang, or switch the shebang "
      "to bash",
      None, Strict, Policy),
    D(3045, "posix-printf-v", "`printf -v` is absent from POSIX printf",
      "The `printf -v` form is a bash extension, and the POSIX `printf` has no "
      "`-v`",
      "Capture the output with a command substitution under a `sh` shebang",
      None, Strict, Policy),
    D(3046, "posix-source",
      "`source` is the bash spelling of the POSIX dot command",
      "The name `source` is the bash spelling of the POSIX `.` command",
      "Use `.` under a `sh` shebang", None, Strict, Policy),
    D(3047, "posix-trap-err", "the `ERR` trap is absent from POSIX sh",
      "The `ERR` condition is a bash extension absent from POSIX sh",
      "Check the status after each command under a `sh` shebang", None, Strict,
      Policy),
    D(3048, "posix-trap-sig-prefix",
      "a SIG prefixed signal name is undefined in POSIX sh",
      "The `SIG` prefix on '{0}' is undefined in POSIX sh",
      "Name the signal without the `SIG` prefix under a `sh` shebang", None,
      Strict, Policy),
    D(3049, "posix-trap-signal-case",
      "a lowercase signal name is undefined in POSIX sh",
      "The signal name '{0}' is not uppercase, and POSIX sh leaves it "
      "undefined",
      "Name the signal in uppercase under a `sh` shebang", None, Strict,
      Policy),
    D(3050, "posix-printf-quote",
      "the `printf` `%q` directive is absent from POSIX sh",
      "The `printf` `%q` directive is a bash extension absent from POSIX sh",
      "Quote the value another way under a `sh` shebang", None, Strict, Policy),
    D(3053, "posix-indirect-expansion",
      "indirect expansion is absent from POSIX sh",
      "The indirect expansion of `{0}` is a bash extension absent from POSIX "
      "sh",
      "Use `eval` or a `case` dispatch under a `sh` shebang", None, Strict,
      Policy),
    D(3054, "posix-array-reference", "arrays are absent from POSIX sh",
      "The array reference `{0}` is a bash extension absent from POSIX sh",
      "Use the positional parameters under a `sh` shebang", None, Strict,
      Policy),
    D(3055, "posix-array-key-expansion",
      "array key expansion is absent from POSIX sh",
      "The array key expansion of `{0}` is a bash extension absent from POSIX "
      "sh",
      "Use the positional parameters under a `sh` shebang", None, Strict,
      Policy),
    D(3056, "posix-name-prefix-expansion",
      "name matching prefixes are absent from POSIX sh",
      "The name prefix expansion of `{0}` is a bash extension absent from "
      "POSIX sh",
      "List the names explicitly under a `sh` shebang", None, Strict, Policy),
    D(3057, "posix-string-indexing", "string indexing is absent from POSIX sh",
      "The substring expansion of `{0}` is a bash extension absent from POSIX "
      "sh",
      "Use `expr` or `cut` under a `sh` shebang", None, Strict, Policy),
    D(3060, "posix-string-replacement",
      "string replacement is absent from POSIX sh",
      "The string replacement in `{0}` is a bash extension absent from POSIX "
      "sh",
      "Use `sed` or a `case` dispatch under a `sh` shebang", None, Strict,
      Policy),
    D(None, "arith-assign", "array syntax was used for arithmetic assignment",
      "The assignment of '{0}' uses array subscript syntax",
      "Use `let '{0}={1}'` to evaluate and assign it", None, Strict, Policy),
    D(None, "arithmetic-xor-power", "the caret operator performs bitwise XOR",
      "The `^` operator performs bitwise XOR in Bash arithmetic",
      "Use `**`, the Bash power operator, if you meant exponentiation", None,
      Annoying, Policy),
    D(None, "assignment-prefix-read",
      "an assignment prefix is read before it takes effect",
      "The variable '{0}' is read before the assignment prefix takes effect",
      None, None, Lenient, Policy),
    D(None, "exported-cdpath",
      "an exported `CDPATH` can redirect child scripts",
      "An exported `CDPATH` can redirect `cd` commands in child scripts",
      "Keep `CDPATH` unexported or clear it before running scripts", None,
      Strict, Policy),
    D(None, "arith-external-input",
      "external input is evaluated as arithmetic code",
      "A value from external input is evaluated as arithmetic code",
      "Validate the value as decimal digits before arithmetic", None, Strict,
      Policy),
    D(None, "array-subscript-external-input",
      "an external array subscript is evaluated as arithmetic code",
      "An array subscript from external input is evaluated as arithmetic code",
      "Validate the subscript as decimal digits before using it", None, Strict,
      Policy),
    D(None, "malformed-glob", "a glob contains an unterminated bracket class",
      "The glob pattern has an unterminated `[`", None, None, Strict, Policy),
    D(None, "no-local", "a function assignment without `local` leaks globally",
      "This assignment to '{0}' in a function has no `local`",
      "Declare it with `local` to keep it inside the function", None, Annoying,
      Policy),
    D(None, "optimizer-eliminated-cstyle-for",
      "a C-style for loop with a zero condition was removed",
      "This C-style `for` loop has a zero condition and never runs its body",
      "Remove the loop or write a condition that can be true", None, Lenient,
      Warning),
    D(None, "optimizer-eliminated-for",
      "a for loop over an empty list was removed",
      "This `for` loop iterates over an empty list and never runs its body",
      "Remove the loop or give it words to iterate over", None, Lenient,
      Warning),
    D(None, "optimizer-eliminated-if",
      "an if with no reachable body was removed",
      "Every condition of this `if` is statically false and it has no `else` "
      "body",
      "Remove the `if` or write a condition that can be true", None, Lenient,
      Warning),
    D(None, "optimizer-folded-arithmetic",
      "a constant arithmetic expression was folded",
      "The arithmetic expression `{0}` is constant and was folded to '{1}'",
      None, None, Lenient, Warning),
    D(None, "optimizer-folded-branch", "an if always takes the same branch",
      "Every condition of this `if` is statically decidable and branch '{0}' "
      "always runs",
      None, None, Lenient, Warning),
    D(None, "optimizer-folded-else", "an if always takes its else body",
      "Every condition of this `if` is statically false and the `else` body "
      "always runs",
      None, None, Lenient, Warning),
    D(None, "optimizer-folded-loop", "a loop condition is statically false",
      "This `{0}` loop condition never lets the body run", None, None, Lenient,
      Warning),
    D(None, "typeset-spelling", "`typeset` is the ksh spelling of `declare`",
      "The `typeset` builtin is the ksh spelling of `declare`",
      "Write `declare` for the bash name", None, Annoying, Policy),
    D(None, "unresolved-command",
      "a command cannot be resolved during analysis",
      "The command '{0}' was not found", "Did you mean '{1}'?", None, Lenient,
      Policy),
    D(None, "unresolved-command-directory",
      "a directory in a command path does not exist",
      "The directory '{0}' does not exist", None, None, Lenient, Policy),
    D(None, "unresolved-command-uncertain",
      "a command may be defined by unseen runtime code",
      "The command '{0}' could not be verified after runtime code",
      "Did you mean '{1}'?", None, Lenient, Warning),
    D(None, "use-before-assign", "a variable is read before a later assignment",
      "The variable '{0}' is read before it is assigned", None,
      "the assignment that gives '{0}' a value runs here", Lenient, Policy),
};

#undef D

static_assert(countof(DIAGNOSTIC_DEFINITIONS) ==
              static_cast<usize>(diagnostic_id::Count));

} /* namespace koshka */
